export const categoryImages: Record<string, string> = {
  Electronics: "/Electronics.jpg",
  "Computers & Laptops": "/computers.jpg",
  "Mobile Phones & Accessories": "/Phones.jpg",
  Gaming: "/gaming.jpg",
  "Home & Kitchen": "/home.jpg",
  Furniture: "/furniture.jpg",
  Fashion: "/Fashion.jpg",
  "Beauty & Personal Care": "/beauty.jpg",
  "Health & Wellness": "/health.jpg",
  "Automotive & Motorcycles": "/automotive.jpg",
  "Sports & Outdoors": "/sports.jpg",
  "Jewelry & Watches": "/jewelry.jpg",
  "Books & Stationery": "/books.jpg",
  "Toys & Hobbies": "/toys.jpg",
  "Pet Supplies": "/pet.jpg",
  "Alcohol & Liquor": "/alcohol.jpg",
  "Food & Groceries": "/food.jpg",
  Beverages: "/beverages.jpg",
  "Smart Home & Robotics": "/robotics.jpg",
  "POS & Retail Equipment": "/pos.jpg",
  "CCTV & Surveillance": "/cctv.jpg",
  "Printing & 3D Printing": "/printer.jpg",
  "Networking & Internet": "/wifi.jpg",
  "Electronics Components & Development": "/robotics.jpg",
  "Electrical & Wiring": "/robotics.jpg",
  "Solar & Renewable Energy": "/solar.jpg",
  "Construction Materials": "/construction.jpg",
  "Tools & Hardware": "/tools.jpg",
  "Motorbike Parts": "/motorbike.jpg",
  "Industrial Equipment": "/industry.jpg",
  "Agriculture & Farming": "/agriculture.jpg",
  "Baby Products": "/kids.jpg",
  "Office & Business Supplies": "/office.jpg",
  "Musical Instruments": "/music.jpg",
  "Intimate Wellness (18+)": "/wellness.jpg",
};
