export const categoryImages: Record<string, string> = {
  Electronics: "/menu/electronics.jpg",
  "Computers & Laptops": "/menu/computers.jpg",
  "Mobile Phones & Accessories": "/menu/phones.jpg",
  Gaming: "/menu/gaming.jpg",
  "Home & Kitchen": "/menu/home.jpg",
  Furniture: "/menu/furniture.jpg",
  Fashion: "/menu/fashion.jpg",
  "Beauty & Personal Care": "/menu/beauty.jpg",
  "Health & Wellness": "/menu/health.jpg",
  "Automotive & Motorcycles": "/menu/automotive.jpg",
  "Sports & Outdoors": "/menu/sports.jpg",
  "Jewelry & Watches": "/menu/jewelry.jpg",
  "Books & Stationery": "/menu/books.jpg",
  "Toys & Hobbies": "/menu/toys.jpg",
  "Pet Supplies": "/menu/pet.jpg",
  "Alcohol & Liquor": "/menu/alcohol.jpg",
  "Food & Groceries": "/menu/food.jpg",
  Beverages: "/menu/beverages.jpg",
  "Smart Home & Robotics": "/menu/robotics.jpg",
  "Solar & Renewable Energy": "/menu/solar.jpg",
  "Construction Materials": "/menu/construction.jpg",
  "Tools & Hardware": "/menu/tools.jpg",
  "Motorbike Parts": "/menu/motorbike.jpg",
  "Industrial Equipment": "/menu/industry.jpg",
  "Agriculture & Farming": "/menu/agriculture.jpg",
  "Baby Products": "/menu/baby.jpg",
  "Office & Business Supplies": "/menu/office.jpg",
  "Musical Instruments": "/menu/music.jpg",
};